import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Job offers Portal',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <header className="py-8 border-solid border-b-[1px] border-gray-600 w-full">
          <h1 className="px-2 lg:px-20 text-3xl font-bold">Job Offers Portal</h1>
        </header>

        <main className='px-2 lg:px-20'>{children}</main>
      </body>
    </html>
  )
}
